# future admins should be added via admin-api.
admin_accounts:
  - role: "bankowner"
    phone: "+16505554334"

ibex:
  url: "https://api-sandbox.poweredbyibex.io"
  email: ""
  password: ""
  webhook:
    uri: "" # external uri defined in overrides
    port: 4008
    secret: "not-so-secret"

bridge:
  enabled: false
  apiKey: "<replace>"
  baseUrl: "https://api.bridge.xyz"
  webhook:
    port: 4009
    publicKeys:
      kyc: "<replace>"
      deposit: "<replace>"
      transfer: "<replace>"
    timestampSkewMs: 300000

# See Foreign Exchange Rates: https://www.firstglobal-bank.com/
exchangeRates:
  USD:
    JMD:
      bid: 150
      ask: 160

cashout:
  enabled: false
  minimum:
    amount: 0
    currency: USD
  maximum:
    amount: 100 # $1
    currency: USD
  accountLevel: 2
  fee: 200 # basis points
  duration: 600 # seconds
  email:
    to: "" # add to the overrides.yaml
    from: "notifications@getflash.io"
    subject: "New Cashout"

sendgrid:
  apiKey: "<replace>"
