#@data/values
---
git_uri: https://github.com/brh28/flash.git
git_branch: ci #! main
git_charts_uri: https://github.com/brh28/charts.git
git_price_uri: https://github.com/brh28/price.git
git_charts_branch: main
git_charts_bot_branch: bot-bump-flash-image
git_price_history_proto_bot_branch: bot-bump-price-history-proto
git_price_realtime_proto_bot_branch: bot-bump-price-realtime-proto

gh_org: brh28
gh_repository: flash
gh_user: ((github.username)) 
gh_password: ((github.api_token)) 
github_token: ((github.api_token))
#! github_app_id: ((github.github_app_id))
#! github_app_private_key: ((github.github_app_private_key))

docker_registry: ((docker.registry)) 
docker_registry_user: ((docker.username))
docker_registry_password: ((docker.password))
#! docker_host_ip: ((staging-ssh.docker_host_ip))

#! artifacts_bucket_name: ((staging-gcp-creds.bucket_name))
#! staging_inception_creds: ((staging-gcp-creds.creds_json))
gcs_creds: ((gcs.sa_creds))

#! staging_ssh_private_key: ((staging-ssh.private_key))
#! staging_ssh_pub_key: ((staging-ssh.public_key))

#! slack_channel: galoy-main-github
#! slack_username: concourse
#! slack_webhook_url: ((galoy-main-slack.api_url))
